urdu:
  test: "../UDTB_pre_release_version-0.01/Intra-chunk/CONLL/utf/Testing/"
  train: "../UDTB_pre_release_version-0.01/Intra-chunk/CONLL/utf/Training/"
  validation: "../UDTB_pre_release_version-0.01/Intra-chunk/CONLL/utf/Development/"
hindi:
  test: "../HDTB_pre_release_version-0.05/IntraChunk/CoNLL/utf/news_articles_and_heritage/Testing/"
  train:  "../HDTB_pre_release_version-0.05/IntraChunk/CoNLL/utf/news_articles_and_heritage/Training/"
  validation: "../HDTB_pre_release_version-0.05/IntraChunk/CoNLL/utf/news_articles_and_heritage/Development/"
output_hindi: 'output/hindi/'
output_urdu: 'output/urdu/'
model_weights:
  1: 'src/model_weights/model'
  2: 'src/model_weights/model_with_phonetic'
  3: 'src/model_weights/model_frozen'
  4: 'src/model_weights/model_with_phonetic_frozen'
hindi_predict_input: 'src/hindi_predict_data/test_data.txt'
urdu_predict_input: 'src/urdu_predict_data/test_data.txt'